export const constantsen = {
  LABEL_FIELD_REQUIRED: 'Required field',
  LABEL_INVALID_EMAIL:  'Invalid Email',
  LABEL_MAX_LENGTH_14:  'Max length allowed is 14 characters',
  LABEL_MIN_LENGTH_8:   'Min length allowed is 8 characters',
  LABEL_MIN_LENGTH_6:   'Max length allowed is 6 characters',
  LABEL_MAX_LENGTH_12:  'Max length allowed is 12 characters',
  LABEL_MAX_LENGTH_50:  'Max length allowed is 50 characters',
  LABEL_MIN_LENGTH_4:   'Max length allowed is 4 characters',
  LABEL_MAX_LENGTH_16:  'Max length allowed is 16 characters',
  LABEL_MIN_LENGTH_10:  'Max length allowed is 10 characters',
  LABEL_MAX_LENGTH_20:  'Max length allowed is 20 characters',
  LABEL_MIN_LENGTH_20:  'Max length allowed is 20 characters',
  LABEL_MAX_LENGTH_400: 'Max length allowed is 400 characters',
  LABEL_MAX_LENGTH_30:  'Max length allowed is 30 characters',
  LABEL_INVALID_WEB: 'Wrong web page address',
  LABEL_INVALID_SOCIAL_NETWORK: 'Wrong social network address',
  LABEL_INVALID_SOCIAL_FACEBOOK: 'Wrong Facebook web address',
  LABEL_INVALID_SOCIAL_TWITTER: 'Wrong Twitter web address',
  LABEL_INVALID_SOCIAL_YOUTUBE: 'Wrong YouTube web address',
  LABEL_INVALID_SOCIAL_INSTAGRAM: 'Wrong Instagram web address',
  LABEL_PASSWORD_NOTMACH: 'Passwords did not match',
  LABEL_PASSWORD: 'Change Password',
  LABEL_SECURITY: 'Security',
  LABEL_UPDATE: 'Update',
  LABEL_AUTH: 'Sign in',
  LABEL_ENTER: 'Enter',
  LABEL_SIGNUP: 'Sign up',
  LABEL_CANCEL: 'Cancel',
  LABEL_TYPE_USER_COMPETITOR: 'Competitor',
  LABEL_TYPE_USER_SPONSORING: 'Sponsor',
  LABEL_LOSTPASSWORD: 'Forgotten password?',
  LABEL_PRIVACY_POLITICS: 'Privacy Policy',
  LABEL_TERMS_AND_CONDITIONS: 'Terms and Conditions',
  LABEL_CLOSE_SESSION: 'Sign out',
  LABEL_CLOSE: 'Close',
  LABEL_SEND_PASSWORD: 'Pasword recovery',
  LABEL_SEND: 'Send',
  LABEL_SIGNIN_FACEBOOK: 'Sign in with Facebook',
  LABEL_SIGNUP_FACEBOOK: 'Sign up with Facebook',
  LABEL_SIGNIN_GOOGLE: 'Sign in with Google',
  LABEL_SIGNUP_GOOGLE: 'Sign up with Google',
  LABEL_CREATE_ACCOUNT: 'Create Account',
  LABEL_NOT_HAVE_ACCOUNT: 'Do not have an account?',
  LABEL_RECOVERY: ' Recover',
  LABEL_BACK_LOGIN: ' Back to sign in',
  LABEL_HAVE_ACCOUNT: 'Already have an account?',
  LABEL_CONFIRM_EMAIL: 'Confirm your Email!',
  LABEL_CONFIRM_SENT: 'We have sent a confirmation Email to your email address.',
  LABEL_CONFIRM_SENT2: 'We have sent you an email with your new password.',
  LABEL_CHECK_EMAIL: 'Please check your inbox and/or verify your spam folder and click on the link ',
  LABEL_CHECK_EMAIL2: '"Enable user" to confirm your email address.',
  // tslint:disable-next-line: max-line-length
  LABEL_CHECK_EMAIL3: 'Please check your inbox and/or verify your spam folder and use the temporary password that we have sent to sign in. ',
  LABEL_CHECK_EMAIL4: 'To change it, edit your profile and set a new password.',
  LABEL_PASSWD_RECOVERED: 'Password recovered',
  LABEL_GO_TO_PANEL: 'Go to Dashboard',
  LABEL_PANEL: 'Dashboard',
  LABEL_CLOSE_SESION: 'Sign out',
  LABEL_HOME: 'Home',
  LABEL_HOWITWORK: 'How it works',
  LABEL_TEAM: 'The team',
  LABEL_SHOP: 'Store',
  LABEL_NEWS: 'News',
  LABEL_CONTACT: 'Contact',
  LABEL_CONTACTUS: 'Contact us.',
  LABEL_JOIN_TELEGRAM: 'Join our Telegram',
  LABEL_CONTACTUS_ASK: 'Questions? Contact us.',
  LABEL_CONTACTUS_ASK2: 'We will answer you shortly.',
  LABEL_RESOURCES: 'Resources',
  LABEL_WHITEPAPER: 'Whitepaper',
  LABEL_LINKS: 'Links',
  LABEL_ROADMAP: 'Roadmap',
  LABEL_TOKEN: 'The token',
  LABEL_SLOGAN: 'SLOGAN',
  LABEL_PROFILE: 'Profile',
  LABEL_CHALLENGE: 'Challenges',
  LABEL_ROUTES: 'Routes',
  LABEL_AWARDS: 'Prizes',
  LABEL_ADS: 'Advertisements',
  LABEL_PAYMENT: 'Payments',
  LABEL_WALLET: 'Wallet',
  LABEL_STADISTICS: 'Stats',
  LABEL_NAME: 'Name',
  LABEL_NAME_CLIENT: 'Client Name',
  LABEL_SYMBOL: 'Symbol',
  LABEL_DECIMALS: 'Decimals',
  LABEL_BLOCKCHAIN: 'Blockchain',
  LABEL_CONTRACT: 'Contract',
  LABEL_EXPLORER: 'Explorer',
  LABEL_DAPP: 'Web Dapp',
  LABEL_CONTENT: 'Content',
  LABEL_SAVE: 'Save',
  LABEL_PERSONAL_INFO: 'Personal Information',
  LABEL_COMPANY_INFO: 'Information',
  LABEL_SOCIAL_NETWORKS: 'Social Networks',
  LABEL_LOGO: 'Logo',
  LABEL_AVATAR: 'Avatar',
  LABEL_MEASUREMENTS: 'Measurements',
  LABEL_ADDRESS: 'Address',
  LABEL_SELECT_IMAGE: 'Select Image',
  LABEL_SIZE_MAX_LOGO: 'Maximum image size 150 Kb',
  LABEL_COMPETITOR_INFO: 'Personal information',
  LABEL_GENDER_FEMME: 'Female',
  LABEL_GENDER_MALE: 'Male',
  LABEL_WEIGHT: 'Weight',
  LABEL_HEIGHT: 'Height',
  LABEL_METERS: 'Meters',
  LABEL_INCH: 'Inches',
  LABEL_KILOGRAMS: 'Kilograms',
  LABEL_EDIT_PROFILE: 'Edit profile',
  LABEL_POUNDS: 'Pounds',
  LABEL_LOADING_PROCESSING: 'Wait, processing',
  LABEL_IN_DEVELOPMENT: 'In development',
  LABEL_COMPLETED: 'Completed',
  LABEL_ENGLISH: 'English',
  LABEL_SPANISH: 'Spanish',

  LABEL_HOME_WELCOME: 'Welcome to SportGift.',
  // tslint:disable-next-line: max-line-length
  LABEL_HOME_1: 'SportGift is a platform integrated by a series of technologies in the cloud, microservices, mobile app, web app and an Ethereum blockchain token, that will allow to its users earn rewards by exercising.',
  LABEL_HOME_2: 'The mobile app will allow competitors participate in challenges and earn prizes.',
  // tslint:disable-next-line: max-line-length
  LABEL_HOME_3: 'The web app will allow sponsor companies create sport challenges, set prizes or promotions and create ad campaigns that will be published in all our media and social networks.',
  // tslint:disable-next-line: max-line-length
  LABEL_HOME_4: 'The SPORTG tokens, will be used to fund the project, as a payment method in the Sportgift store, to pay ads by the sponsors, to growth affiliations and to exchange the token in major crypto-exchangers.',
  LABEL_ROADMAP_WEB_1: 'Creation of the system\'s architecture',
  LABEL_ROADMAP_WEB_2: 'Definition of styles and web layers',
  LABEL_ROADMAP_WEB_3: 'Definition of security layer',
  LABEL_ROADMAP_WEB_4: 'Creación de términos y condiciones',
  LABEL_ROADMAP_WEB_5: 'Development of system modules',
  LABEL_ROADMAP_WEB_6: 'Integration with social networks',
  LABEL_ROADMAP_WEB_7: 'Creation of web services',
  LABEL_ROADMAP_WEB_8: 'Integration of payment gateway',
  LABEL_ROADMAP_WEB_9: 'QA Tests',
  LABEL_ROADMAP_WEB_10: 'System Marketing',

  LABEL_ROADMAP_MOVIL_1: 'Defition of the App\'s architecture',
  LABEL_ROADMAP_MOVIL_2: 'Definition of styles and layers',
  LABEL_ROADMAP_MOVIL_3: 'UI Modeling',
  LABEL_ROADMAP_MOVIL_4: 'Web services integration',
  LABEL_ROADMAP_MOVIL_5: 'Development of the security layer',
  LABEL_ROADMAP_MOVIL_6: 'Integration with the payment gateway',
  LABEL_ROADMAP_MOVIL_7: 'QA tests',
  LABEL_ROADMAP_MOVIL_8: 'Play Store deployment',
  LABEL_ROADMAP_MOVIL_9: 'App Store deployment',
  LABEL_ROADMAP_MOVIL_10: 'App marketing',

  LABEL_ROADMAP_GATEWAY_1: 'Choosing the tech to be used',
  LABEL_ROADMAP_GATEWAY_2: 'Creation of the project\'s architecture',
  LABEL_ROADMAP_GATEWAY_3: 'Definition of modules and functionalities',
  LABEL_ROADMAP_GATEWAY_4: 'Creation of the security layer',
  LABEL_ROADMAP_GATEWAY_5: 'REST web services exposure',
  LABEL_ROADMAP_GATEWAY_6: 'External API integrations',
  LABEL_ROADMAP_GATEWAY_7: 'Blockchain integrations',
  LABEL_ROADMAP_GATEWAY_8: 'QA tests',
  LABEL_WALLET_ETHEREUM: 'Wallet Ethereum',
  LABEL_BALANCE: 'Balance',
  LABEL_REFRESH_BALANCE: 'Refresh balance',
  LABEL_COMPETITOR: 'For competitors',
  LABEL_COMPANY: 'For companies',
  LABEL_TASK: 'Tasks',

  LABEL_TITLE_NEWS: 'Find the latest news of SportGift',
  LABEL_OPEN: 'Open',
  LABEL_SHARE: 'Share',
  LABEL_BUY: 'Buy',
  LABEL_SELL: 'On sale',
  LABEL_TITLE_STORE: 'Welcome to our virtual store',

  LABEL_PRICE: 'Price',
  LABEL_MIN_BUY: 'Minimum purchase ammount',
  LABEL_AMMOUNT: 'ammount',
  LABEL_TOTAL: 'Total',
  LABEL_PAY: 'Pay',
  LABEL_WARNING_PAY: 'Must be signed in',
  LABEL_VIEW_DETAIL: 'Detail',
  LABEL_SELECT_FORM_PAYMENT: 'Select payment method',
  LABEL_CHECKOUT_PAY: 'Proceed to checkout',
  LABEL_QUESTION_TRANSACTION: 'Do you want to proceed with your payment ?',
  LABEL_QUESTION_YES: 'Yes',
  LABEL_QUESTION_NO: 'No',
  LABEL_CANCEL_TRANSACTION: 'Cancel payment',
  LABEL_CLOSE_WINDOW: 'Close',
  LABEL_TIME_LEFT: 'Time left',
  LABEL_SECONDS: 'Seconds',
  LABEL_TRANSACTION: 'Transaction created',
  LABEL_QUESTION_ANUL_TRANSACTION: 'Do you want to abort the payment?',
  LABEL_VIEW_TRANSACTION: 'View transaction',


  PLACEHOLDER_TYPE_MEASUREMENT_HEIGHT: 'Enter height measurements',
  PLACEHOLDER_TYPE_MEASUREMENT_WEIGHT: 'Enter weight measurements',
  PLACEHOLDER_OLD_PASSWORD: 'Type your now password',
  PLACEHOLDER_NEW_PASSWORD: 'Type your new password',
  PLACEHOLDER_COMPETITOR_NAME: 'Contestant name',
  PLACEHOLDER_FORMPAYMENT: 'Payment method',
  PLACEHOLDER_NAME: 'Name',

  SUBJECT_LOST_EMAIL : 'Password recovered',
  SUBJECT_SIGNUP_SUCCESSFULL : 'You have been succesfully registered in Utopia ',
  SUBJECT_SEND_COMMENTS : 'Comment sent',

  MSG_SUCCESSFULL_SAVE_PROFILE: 'Profile saved successfully',
  MSG_SUCCESSFULL_AUTH: 'Successfully signed in',
  MSG_SUCCESSFULL_SIGNUP: 'Successfully signed up',
  MSG_SUCCESSFULL_PASSWORD_CHANGED: 'Password changed successfully',
  MSG_SUCCESSFULL_SEND_PASSWORD: 'We have sent an email with instructions to recover your password',
  MSG_SUCCESSFULL_CLOSE: 'You are signed out',
  MSG_SUCCESSFULL_ACTIVATED: 'User created successfully',
  MSG_SUCCESS_ACTIVATE: 'Your user account was successfully activated. ',
  MSG_SUCCESS_ACTIVATE2: 'To access the system please use your credentials to sign in. ',
  MSG_SUCCESS_SAVE_AVATAR: 'Avatar saved successfully ',
  MSG_SUCCESS_SAVE_LOGO: 'Logo saved successfully ',
  MSG_SUCCESSFULL_SEND_COMMENT: 'Comment sent successfully, we\'ll reach you back shortly.',
  MSG_SUCCESS_TRANSACTION: 'Transaction generated successfully',
  MSG_SUCCESS_ANUL_TRANSACTION: 'Transaction cancelled successfully',
  MSG_WARNING_TIMEOUT_TRANSACTION: 'Previous transaction timed out',
  MSG_SUCCESSFUL_TRANSACTION: 'Transaction processed successfully, we\'ve sent an email with the transaction info.',

  MSG_ERROR_PASSWORD_NOT_MATCH: 'The previous password is incorrect',
  MSG_ERROR_AUTH: 'Wrong user or password',
  MSG_ERROR_PASSWORD_NOMATCH: 'Password confirmation do not match',
  MSG_ERROR_REPEAT_USER: 'User name provided is already registered',
  MSG_ERROR_REPEAT_EMAIL: 'Email provided is already registered',
  MSG_ERROR_REGISTERED_SOCIAL: 'You are already registered, please sign in',
  MSG_ERROR_EMAIL_EXIST_SOCIAL: 'Someone has already registered with the email you are using linked to a social network',
  MSG_ERROR_SESSION_INVALID: 'Error: session expired. Please sign in again.',
  MSG_ERROR_SESSION_INVALID_NR: 'Error: session expired. Please sign in again',
  MSG_LOST_PASSWORD: 'Please enter your email to recover your password',
  MSG_ERROR_EMAIL_NOT_FOUND: 'The provided Email is not registered in our system',
  MSG_ERROR_NOT_REGISTERED_SOCIAL: 'You have not been registered yet, please sign up',
  MSG_ERROR_USER_INACTIVE: 'User inactive',
  MSG_ERROR_USER_NOT_FOUND: 'User not found',
  MSG_ERROR_SEND_EMAIL: 'Something went wrong sending your email, please retry later',
  MSG_ERROR_USER_ACTIVE: 'User is already active',
  MSG_ERROR_USER_ACTIVATE: 'Something wen wrong activating the user',
  MSG_ERROR_ID_NOT_FOUND: 'User ID was not set in your request. ',
  MSG_ERROR_ID_NOT_FOUND2: 'Please double check your activation link and try again.',
  MSG_ERROR_ACTIVATE: 'Something went wrong while trying to activate the user. ',
  MSG_ERROR_ACTIVATE_NOT_FOUND: 'User not found in the system. ',
  MSG_ERROR_ACTIVATE_USER_ACTIVE: 'User is already active, please use your credentials to sign in. ',
  MSG_ERROR_SAVE_PROFILE: 'Something went wrong while saving the profile',
  MSG_ERROR_DATA_PROFILE: 'Error while getting profile data',
  MSG_ERROR_DATA_COUNTRY: 'Error obtaining country data',
  MSG_ERROR_DATA_CITY: 'Error obtaining city data',
  MSG_ERROR_IMAGEN_SIZE: 'Image exceeds the maximum allowed size 150Kb',
  MSG_ERROR_SAVE_IMAGE_PROFILE: 'Something went wrong when trying to save your profile picture',
  MSG_ERROR_USER_SOCIAL_NETWORK: 'Your account belogs to a social network, you can\'t change your password using this system',
  MSG_ERROR_LOGIN_SOCIAL_NETWORK: 'Your account belongs to a social network, you must use the social buttons to sign in',
  MSG_ERROR_HEIGHT: 'Enter height value',
  MSG_ERROR_SELECT_HEIGHT: 'Choose height type',
  MSG_ERROR_WEIGHT: 'Choose weight value',
  MSG_ERROR_SELECT_WEIGHT: 'Choose weight type',
  MSG_ERROR_MEASUREMENTS: 'There are some errors in the measurements section, please verify',
  MSG_ERROR_AUTHENTICATED: 'You are already signed in, you cannot access this module',
  MSG_ERROR_SEND_COMMENT: 'Somthing went wrong sending your comment, please retry later',
  MSG_ERROR_PASSWORD_SAME_OLD: 'The new password is equal to your previous password, please update it',
  MSG_ERROR_ACCESS_INVALID: 'Invalid access',
  MSG_ERROR_CAPTCHA: 'Your Google V3 captcha was not approved, please retry',
  MSG_ERROR_GET_WALLET: 'Error while obtaining wallet',
  MSG_ERROR_MAX_REQUEST_WALLET: 'You have made many consecutive requests, please wait a few minutes',
  MSG_ERROR_USER_INVALID: 'Wrong user name or password',
  MSG_ERROR_ID_NEWS: 'Somthing went wrong, the news ID was not delivered, redirecting.',
  MSG_ERROR_NEWS_NOT_FOUND: 'Than news cannot be found',
  MSG_ERROR_ARTICLE_NOT_FOUND: 'Error article not found',
  MSG_ERROR_EMAIL_REQUIRED_SOCIAL: 'Error during registration, your social network account does not have an email associated',
  MSG_ERROR_API_PRECIO: 'Error getting prize, please try again later',
  MSG_ERROR_CANCEL_TRANSACTION: 'Error cancelling the transaction, please retry later',
  // tslint:disable-next-line: max-line-length
  MSG_ERROR_TIMEOUT_TRANSACTION: 'Transaction timeout. You have not sent the coins in the required time',
  MSG_ANUL_TRANSACTION: 'The payment transaction has been cancelled',

  MSG_ERROR_CRYPTO_SELECT: 'You must select a currency',

  ROLE_COMPETITOR: 'USER_ROLE',
  ROLE_COMPANY: 'SPONSORING_ROLE',
  

  TITLE_ERROR_ACTIVATE_USER: 'Error activating user!',
  TITLE_ACTIVATE_USER_SUCESS: 'User activation successful!',
  TITLE_SMART_CONTRACT: 'Our Smart Contract',
  TITLE_INFO_CONTRACT: 'Token',

  PLACEHOLDER_USERNAME: 'User',
  PLACEHOLDER_COMPANY_NAME: 'Name',
  PLACEHOLDER_EMAIL: 'Email',
  PLACEHOLDER_CLIENT_EMAIL: 'Cient Email',
  PLACEHOLDER_TYPEUSER: 'User type',
  PLACEHOLDER_PASSWORD: 'Password',
  PLACEHOLDER_REPEAT_PASSWORD: 'Confirm password',
  PLACEHOLDER_RIC_RUC: 'Rif or Ruc',
  PLACEHOLDER_WEB: 'Website',
  PLACEHOLDER_LOGO: 'Logo',
  PLACEHOLDER_TWITTER: 'Twitter',
  PLACEHOLDER_FACEBOOK: 'Facebook',
  PLACEHOLDER_INSTAGRAM: 'Instagram',
  PLACEHOLDER_SNAPCHAT: 'Snapchat',
  PLACEHOLDER_COUNTRY: 'Country',
  PLACEHOLDER_CITY: 'City',
  PLACEHOLDER_ADDRESS: 'Address',
  PLACEHOLDER_PHONE: 'Residential phone',
  PLACEHOLDER_MOVIL: 'Mobile phone',
  PLACEHOLDER_BIRTHDATE: 'Birth date',
  PLACEHOLDER_GENDER: 'Gender',
  PLACEHOLDER_YOUTUBE: 'Youtube',

  ICON_EMAIL: 'mail_outline',
  ICON_ERROR: 'highlight_off',
  ICON_SUCCESS: 'check',
  ICON_TIEMOUT: 'timer',
  

  CONTENT_CONTACT: 'Contact us',
  CONTENT_ASK1: 'Any question? Contact us',
  CONTENT_ASK2: 'And we will answer shortly.',
  CONTENT_PHON: '+000 000 000 00',
  CONTENT_EMAIL: 'info@sportgift.io',
  CONTENT_JOIN_TELEGRAM: 'Join our Telegram @sportgift_official',

  CONTENT_SPORTGIFT_ROADMAP: 'SportGift Roadmap 2020',
  CONTENT_APP_WEB: ' Web Application ',
  CONTENT_APP_MOVIL: 'Mobile app ',
  CONTENT_GATEWAY: 'Payment gateway',
  CONTENT_WHITEPAPER: 'SportGift whitepaper',
  CONTENT_TITLE_ROADMAP: 'SportGift roadmap ',
  // tslint:disable-next-line: max-line-length
  CONTENT_DESCRIPTION_ROADMAP: 'Our roadmap offers a general vision of our upcoming projects, plans, milestones, and more. Take a look into the things we are working with.',
  CONTENT_TAREAS: 'Tasks',
  // tslint:disable-next-line: max-line-length
  CONTENT_COMPLETED: 'Completed',
  // tslint:disable-next-line: max-line-length
  CONTENT_DESC_WEB: 'Sportgift web app is a platform in the cloud developed with the latest technologies, it will allow the sponsoring companies to register and be able to set challenges, create ad campaigns, publish challenges, edit profiles and check stats among other things. Also, it will allow the contestants edit their profiles, check stats and wallets.',
  // tslint:disable-next-line: max-line-length
  CONTENT_DESC_WEB2: 'In the website, we will pubish important announcements about the project and the token, so as relevant information about the app. This module is an esencial part of the 4 components of the project: Web app, mobile app, payment gateway and project token.',
  // tslint:disable-next-line: max-line-length
  CONTENT_DESC_MOVIL: 'The mobile app is a crucial base of the project and will allow to users participate in sport challenges, follow-up the roadmap, request prizes, participate in competitions with relatives and friends in social networks, watch latest news, among other cool features that we have considered to develop alongside the project.',
  // tslint:disable-next-line: max-line-length
  CONTENT_DESC_GATEWAY: 'The payment gateway is the transactional engine inside the platform, it will allow contestants and sponsors use the SPORTG token to exchange it for items available in the virtual store, challenges, pay advertisements inside the app, withdraw tokens to a wallet, among other things, the tokem will be available in major exchanges.',
  // tslint:disable-next-line: max-line-length
  CONTENT_DESC_WHITEPAPER: 'The SportGift\'s whitepaper is an exelent place to learn more about the project, it describes everything you need to know, from the SportGift\'s mission and vission to the details about how the app will work. If you want to dive in more in SportGift and really understand exactly what we represent, download our whitepaper to start.',

  INFOCOMPETITOR: 'infocompetitor-en.png',
  INFOCOMPANY: 'infocompany-en.png',

  LABEL_NOT_HAVE_CODE: 'Have not you received the code?',
  LABEL_RESEND_CODE: 'Resend code',
  LABEL_ENTER_CODE: 'Enter VERIFICATION CODE sent to your email',
  LABEL_TEXT_CODE : '* Code: 5 digit number sent to your email, valid for 3 minutes',
  LABEL_MIN_LENGTH_5:   'Max length allowed is 5 digits',
  SUBJECT_ACCESS_CODE : 'Access code',
  MSG_ERROR_USER_CODE: 'Wrong Access Code',
  MSG_ERROR_MINUTES_EXCEED: 'Access code expired',
  LABEL_PARNERTS: 'PARTNERS',  
  LABEL_CONFIG: 'Configuration',
  LABEL_TRANSACTIONS: 'Transactions', 
  LABEL_BLOCKCHAINS: 'Blockchains',
  LABEL_RESULT: 'Response',
  LABEL_CONFIGURATION: 'Configuration',  
  LABEL_PARAMETER: 'Parameters', 
  LABEL_TEXT_PARAMETERS_NOTE : 'Nota',
  LABEL_TEXT_PARAMETERS : 'La dirección url invocada deberia construirse con los parámetros en el orden como se ven y sustituyendo los valores correspondientes por los propios',
  LABEL_TEXT_PARAMETERS_ONE: 'In order to charge your clients using your Payments Gateway, you need to create a URL calling the TovaGateway  with a series of parameters like the ones shown on the table and following the same order.',
  LABEL_POSITION: 'Order',   
  LABEL_MANDATORY: 'Mandatory', 
  LABEL_DESCRIPTION: 'Description', 
  LABEL_DESCRIPTION_PROFILE_ID: 'Is the identifier of the profile that will be used to associate the payments made from your clients to your store. It can be found when editing your profile.', 
  LABEL_DESCRIPTION_AMOUNT: 'Amount in dollars to be paid, it must be a number and decimals separated by dots. Example 41.05', 
  LABEL_DESCRIPTION_BUYER_NAME: 'Is the name of the buyer that will be displayed on screen and on the email to be sent.', 
  LABEL_DESCRIPTION_BUYER_EMAIL: 'Purchaser email, is a mandatory field.', 
  LABEL_DESCRIPTION_DESCRIPTION: 'Description about what are you paying, this is optional.', 
  PLACEHOLDER_PROFILE_ID: 'Profile ID',
  LABEL_YES: 'Yes',
  LABEL_NO: 'No',
  LABEL_DESCRIPTION_PURCHASE_ID: 'Buying cart ID or purchase ID, is used to send the answer and notify to your store the final result of the transaction.',
  MSG_ERROR_API_BLOCKCHAINS:  'Error getting blockchains available',
  LABEL_TEXT_BLOCKCHAINS:'Choose the blockchains that will be used to receive payments',
  MSG_ERROR_UPDATE_BLOCKCHAINS:'Something went wrong updating blockchains',
  MSG_SUCCESSFULL_UPDATED: 'Successfully updated',
  LABEL_SUSTITUTE_URL: 'Replace the corresponding values for tha appropriate', 

  LABEL_ERROR_PROFILE_ID: 'Parameter profileID is invalid',
  LABEL_ERROR_AMOUNT: 'Amount payment parameter is invalid ',
  LABEL_ERROR_PURCHASE_ID: 'Purchase ID parameter is invalid ',
  LABEL_ERROR_BUYER_NAME:  'Buyer name parameter is invalid',
  LABEL_ERROR_BUYER_EMAIL: 'Buyer email parameter is invalid',
  LABEL_ERROR_DESCRIPTION: 'Description is invalid',
  LABEL_CLIENT_DATA: 'Client',
  LABEL_AMOUNT_SEND: 'Send',
  PLACEHOLDER_DESCRIPTION: 'Payment description',
  LABEL_STORE_DATA:'Company',
  LABEL_PAYMENT_ACTION: 'Payment',
  LABEL_PRICE_OF: 'Price of ',
  LABEL_AMOUNT_PAY: 'Amount',
  MSG_ERROR_PROFILE_NOT_FOUND: 'Profile ID not found',
  MSG_ERROR_CRYPTOS_NOT_FOUND: 'There are not cryptocurrencies configured for this account',
  MSG_SUCCESS_TRANSACTION_ANULATED: 'Payment cancelled succesfully',
  MSG_ERROR_TRANSACTION: 'Error encountered while creating the transaction, try again later.',
  MSG_ERROR_TRANSACTION_NOT_FOUND: 'Transaction not found',
  LABEL_CHECK_TRANSACION: 'Check payment',
  LABEL_SEND_ISSUE: 'Report an issue',
  LABEL_VALUE_TO_PAY:'Amount to pay',
  LABEL_SPAIN: 'Spain',
  LABEL_HOME_INTRO: 'Our complete solution to receive and process payments',
  LABEL_HOME_INTRO_2: '',
  LABEL_HOME_INTRO_3: 'To use the payment gateway as a merchant, sign up, enter to your user account and review the benefits of the system. Currently we are on testing and development for this reason some modules still under construction',
  LABEL_HOME_INTRO_4:'',
  LABEL_HOW_IT_WORK1: 'How does TovaGateway works?',
  LABEL_HOW_IT_WORK2: 'You would receive payments of third parties with cryptocurrencies by using the TovaGateway which is our payment gateway and one of our star products that you can use on a very simple way following the steps below: ',
  LABEL_HOW_IT_WORK3: 'To use the payment gateway you must redirect your clients to TovaGateway , creating a URL with some specific parameters that you will find when you access your account the section [Configuration -> Parameters]',
  LABEL_HOW_IT_WORK4: '1. Create a user account by signing up on TovaGateway ',
  LABEL_HOW_IT_WORK5: '2. Activate your user account by clicking the link that will be sent to your email',
  LABEL_HOW_IT_WORK6: '3. Configure your profile choosing the coins that you will accept in your store',
  LABEL_HOW_IT_WORK7: '4. In your store or system set up the URL to receive payments using TovaGateway ',
  LABEL_HOW_IT_WORK8: '5. Check all your payments on TovaGateway when you have received them',
  LABEL_HOW_IT_WORK9: '6. Withdraw your funds',
  LABEL_IN_CONSTRUCTION: 'We are developing this module',
  LABEL_EXAMPLE: 'Example', 
  LABEL_NAME_PARAM:'Parameter name',
  LABEL_PRICE_REFRESH: 'Price will be refreshed on',
  MSG_ERROR_INVALID_EMAIL: 'Entered email is not valid',
  TOTAL_FUNDS:  'GLOBAL BALANCE (USD)',
  TRANSACTIONS_HISTORY: 'Last 10 transactions',
  LABEL_DATE: 'Date',
  LABEL_AMOUNT: 'Amount',
  LABEL_CLIENT: 'Client',
  LABEL_STATUS: 'Status',
  LABEL_CRYPTO: 'Cryptocurrency',
  LABEL_CHECK_TRANSACTION: 'Check payment',
  LABEL_TRANSACTION_ID: 'Payment ID',
  LABEL_MSG_TRANSACTION: 'Enter your transaction identifier sent to your email',
  LABEL_QUERY: 'Check it',
  LABEL_TRANSACTION_DATA: 'Payment data',
  LABEL_CREATION_DATE: 'Creation date',
  LABEL_CRYPTO_TO_SEND: 'Crypto to send',
  LABEL_WALLET_TRANSACTION: 'Wallet ',
  LABEL_STATUS_TRANSACTION: 'Status',
  LABEL_PROCESS_ON: 'Processed on', 
  LABEL_CHECK_ANOTHER: 'Check another', 
  LABEL_TRANSACTION_CANCEL: 'Transaction canceled',
  LABEL_TRANSACTION_TIMEOUT: 'Timeout',
  LABEL_TRANSACTION_ERROR: 'Transaction with errors',
  LABEL_TRANSACTION_SUCESSFULL: 'Sucessfull',
  LABEL_TRANSACTION_INCOMPLETE: 'Incomplete',
  MSG_TRANSACTION_FOUND: 'Transaction found and active',
  LABEL_SELECT: 'Select',
  LABEL_VIEW_DETAILS: 'Details',

  STATUS_TRANSACTION_PENDENT: 'Pendent',  
  STATUS_TRANSACTION_SUCESSFULL: 'Sucessfull',
  STATUS_TRANSACTION_INCOMPLETE: 'Incomplete',
  STATUS_TRANSACTION_CANCEL: 'Canceled',
  STATUS_TRANSACTION_TIMEOUT: 'Timeout',
  STATUS_TRANSACTION_ERROR: 'Error',
  LABEL_VALUE: 'Value',
  LABEL_ACTION:'Action',
  LABEL_BOUGHT: 'bought',  
  LABEL_TYPE_USER_BUSSINESS: 'Bussiness',
  LABEL_TYPE_USER_PERSON: 'Personal'

}