export const global = {
  //URLBASE_API: 'https://api-tova.herokuapp.com/api',
  //URLBASE_FRONT: 'https://front-tova.herokuapp.com',
  //profileID : '618597141c484f0016b5d406',

  URLBASE_API: 'http://localhost:3001/api',
  URLBASE_FRONT: 'http://localhost:4200',
  profileID : '620a8c6ac82d416b64257872', 

  ROUTE_LOGIN: 'signin',
  ROUTE_SIGNUP: 'signup',
  ROUTE_HOME: 'home',
  ROUTE_SIGNUPSUCCESS: 'signup_successfull',
  ROUTE_DASHBOARD: 'panel',
  ROUTE_PASSWORDRECOVERY: 'recovery_password',
  ROUTE_RECOVERYSUCCESS: 'sent_successful',
  ROUTE_ACTIVATE_USER_SUCCESS: 'activate_user',
  ROUTE_DASHBOARD_HOME: 'home_dashboard',
  ROUTE_PANEL_HOME: 'panel/home_dashboard',
  ROUTE_CONFIGURATION: 'configuration',
  ROUTE_COMPANY_PROFILE: 'profile',
  ROUTE_TRANSACTIONS: 'transactions', 
  ROUTE_WALLET: 'wallet',
  ROUTE_PAYMENTS: 'payments',
  ROUTE_SECURITY: 'security',
  ROUTE_HOW_IT_WORK: 'how_it_work',
  ROUTE_CONTACT: 'contact',
  ROUTE_TERMS: 'terms',
  ROUTE_PRIVACY: 'privacity_politics',
  ROUTE_BUY: 'comprar',
  LANGUAGE_ES: 'ES',
  LANGUAGE_EN: 'EN',
  ROLE_USER: 'PERSONAL_ROLE',
  ROLE_ADMIN: 'ADMIN_ROLE',
  ROLE_BUSSINESS: 'BUSSINESS_ROLE',
  BLOCKCHAIN_ETHEREUM: 'eth',
  BLOCKCHAIN_BINANCE: 'bsc',
  BLOCKCHAIN_TRON: 'tron',
  ROUTE_GATEWAY: 'gateway',
  ROUTE_PAYMENT: 'payment',
  ROUTE_CHECK_TRANSACTION: 'check_transaction',
  
  STATUS_TRANSACTION_PENDENT: 1,  
  STATUS_TRANSACTION_SUCESSFULL: 4,
  STATUS_TRANSACTION_INCOMPLETE: 5,
  STATUS_TRANSACTION_CANCEL: 2,
  STATUS_TRANSACTION_TIMEOUT: 3,
  STATUS_TRANSACTION_ERROR:6,
   
};
